application: mm-report-website
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.application
  login: required

#- url: /_ah/login_required
#  script: do_openid_login.app

- url: /stylesheets
  static_dir: stylesheets

libraries:
- name: webapp2
  version: latest

